server:
  port: 8088

spring:
  datasource:
    username: root
    password: Mn_950117_
    url: jdbc:mysql://localhost/sjy?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ssm.swagger.entity
  configuration:
    map-underscore-to-camel-case: true


#showSql
logging:
  level:
    com.ssm.swagger: debug
  file:
    path: